Caps And Crafting
DesertRose2/desertrose pull request #348
Opened 2021-04-06 15:23 UTC by chowdermcarthor

Simplifies the trading outpost, both in use and in code; makes it far easier to both sell items, and add values to items in order to be sold, in order to better stimulate a healthy caps economy.
Also adds back in wasteland food crafting.

2021-04-06 15:28 UTC, chowdermcarthor commented
The heck does this even *mean*

2021-04-07 21:28 UTC, Superballs69 commented
Howdy! Please resolve the CI checks involving finding space indentations

` code/datums/components/crafting/recipes/wastelandfood.dm:    	/obj/item/reagent_containers/food/snacks/meat/steak/squirrel = 1,
code/datums/components/crafting/recipes/wastelandfood.dm:    	/obj/item/reagent_containers/food/snacks/grown/carrot = 1,
code/datums/components/crafting/recipes/wastelandfood.dm:    	/obj/item/reagent_containers/food/snacks/grown/potato = 1,
code/datums/components/crafting/recipes/wastelandfood.dm:    	/obj/item/reagent_containers/glass/bowl = 1`

Then fill the changes out using the template that was originally given to you when you made the PR.

2021-04-08 14:48 UTC, MarinaGryphon requested changes

2021-04-08 14:48 UTC, MarinaGryphon commented on code/game/objects/items.dm
> +	var/Value = 0 //For purposes of selling things at the wasteland vendor
don't capitalise vars. use `var/caps_value` or something.

2021-04-09 15:51 UTC, chowdermcarthor commented
> Howdy! Please resolve the CI checks involving finding space indentations
> 
> ` code/datums/components/crafting/recipes/wastelandfood.dm: /obj/item/reagent_containers/food/snacks/meat/steak/squirrel = 1, code/datums/components/crafting/recipes/wastelandfood.dm: /obj/item/reagent_containers/food/snacks/grown/carrot = 1, code/datums/components/crafting/recipes/wastelandfood.dm: /obj/item/reagent_containers/food/snacks/grown/potato = 1, code/datums/components/crafting/recipes/wastelandfood.dm: /obj/item/reagent_containers/glass/bowl = 1`
> 
> Then fill the changes out using the template that was originally given to you when you made the PR.

Alright, I'll work on this today - I haven't had time.
Do you want me to list every crafting item added? It's just a port of the old ones from before the rebase.

2021-04-09 16:04 UTC, closed without merging